import { type ThreeElements } from "@react-three/fiber";
import useParticlesMaterial from "./hooks/use-particles-cursor-material";
import { particlesCursorConfig as config } from "./config";
import { DoubleSide } from "three";
import { useParticlesCursorControls } from "./hooks/use-particles-cursor-controls";
import { useParticlesCursorCanvas } from "./hooks/use-particles-cursor-canvas";

export default function ParticlesCursor(props: ThreeElements["group"]) {
  const { resourcesRef, handleCursorMovement } = useParticlesCursorCanvas();
  const material = useParticlesMaterial(resourcesRef);
  useParticlesCursorControls(material?.uniforms);

  return (
    <group scale={0.8} position-y={-0.15} {...props}>
      {/*
       * Particles
       */}
      <sprite count={config.particleCount}>
        <spriteNodeMaterial {...material?.nodes} />
      </sprite>

      {/*
       * Interactive Plane --- Keeps track of the cursor to update the displacement map generated by the 2d canvas
       */}
      <mesh onPointerMove={handleCursorMovement} visible={false}>
        <planeGeometry args={[1.92, 1.92]} />
        <meshBasicNodeMaterial side={DoubleSide} color="red" />
      </mesh>
    </group>
  );
}
